# Lists all RR types available
# Sorted alpha, and most used first
# YMMV

RR_TYPES = Hash[
  "A"         , { :description => "Address record", :active => true },
  "AAAA"      , { :description => "IPv6 address record", :active => true },
  "CNAME"     , { :description => "Canonical name record", :active => true },
  "LOC"       , { :description => "Location record", :active => true },
  "MX"        , { :description => "mail exchange record", :active => true },
  "NS"        , { :description => "name server record", :active => true },
  "PTR"       , { :description => "pointer record", :active => true },
  "SOA"       , { :description => "start of [a zone of] authority record", :active => true },
  "SSHFP"     , { :description => "SSH Public Key Fingerprint", :active => true },
  "TXT"       , { :description => "Text record", :active => true },
  "AFSDB"     , { :description => "AFS database record", :active => true },
  "APL"       , { :description => "Address Prefix List", :active => true },
  "CERT"      , { :description => "Certificate record", :active => true },
  "DHCID"     , { :description => "DHCP identifier", :active => true },
  "DLV"       , { :description => "DNSSEC Lookaside Validation record", :active => true },
  "DNAME"     , { :description => "delegation name", :active => true },
  "DNSKEY"    , { :description => "DNS Key record", :active => true },
  "DS"        , { :description => "Delegation signer", :active => true },
  "HIP"       , { :description => "Host Identity Protocol", :active => true },
  "IPSECKEY"  , { :description => "IPsec Key", :active => true },
  "KEY"       , { :description => "key record", :active => true },
  "KX"        , { :description => "Key eXchanger record", :active => true },
  "NAPTR"     , { :description => "Naming Authority Pointer", :active => true },
  "NSEC"      , { :description => "Next-Secure record", :active => false },
  "NSEC3"     , { :description => "NSEC record version 3", :active => false },
  "NSEC3PARAM", { :description => "NSEC3 parameters", :active => false },
  "RRSIG"     , { :description => "DNSSEC signature", :active => true },
  "RP"        , { :description => "Responsible person", :active => true },
  "SIG"       , { :description => "Signature", :active => true },
  "SPF"       , { :description => "Sender Policy Framework", :active => true },
  "SRV"       , { :description => "Service locator", :active => true },
  "TA"        , { :description => "DNSSEC Trust Authorities", :active => true },
  "TKEY"      , { :description => "secret key record", :active => true },
  "TLSA"      , { :description => "TLSA certificate association", :active => true },
  "TSIG"      , { :description => "Transaction Signature", :active => true },
  ] # RR_TYPES